version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: kigula
      POSTGRES_USER: kigula
      POSTGRES_PASSWORD: changeme
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    env_file: .env
    depends_on:
      - backend
    ports:
      - "2000:2000"

  print-agent:
    build: ./print-agent
    env_file: .env
    depends_on:
      - redis
    ports:
      - "8010:8010"

volumes:
  db-data:
